name: CI

on:
  push:
    branches:
      - main  # Run this workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # Run this workflow on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Adjust as necessary

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Adjust this if your dependencies are listed differently

    - name: Run imgin script
      run: |
        python imgin.py  # Adjust this to your script's entry point
